"""Meari IoT command and property code constants, decoded from the vendor apps."""

# --- IOT CONSTANTS - COMPLETE LIST ---

USER_ID = 1  # (String) userId / Account ID
DEVICE_KEY = 3  # (String) deviceKey / Unique key
REFRESH_FACE_LIST = 14  # (Action) trigger face list refresh
SAFE_PWD = 21  # (String) safePwd / Security password
# NOTE: the app parser maps 50 -> setDeviceName and 61 -> setSnNum, i.e. the
# opposite of the names used here. Unverified; nothing in the integration reads
# either constant, so they are left as-is rather than renamed on one data point.
SN = 50  # (String) Serial Number (app: deviceName)
FIRMWARE_CODE = 51  # (String) firmwareCode
FIRMWARE_VERSION = 52  # (String) firmwareVersion
CLOUD_UPLOAD_ENABLE = 53  # (Int) 0: Off, 1: On (cloudUploadEnable)
HUNT_FIRMWARE_VERSION = 53  # (String) firmware version for hunting cameras
TIME_ZONE = 54  # (String) e.g., "GMT+01:00"
MAC = 56  # (String) Mac address
LAST_CHECK_TIME = 60  # (String) last check timestamp
LICENSE_ID = 61  # (String) licenseId (app: snNum -- see the note on SN above)
SUPPORT_VERSION = 62  # (String) protocol support version
DEVICE_MODEL = 63  # (String) deviceModel (e.g., "Speed 4S")
PLATFORM_CODE = 64  # (String) platformCode
DEVICE_ONLINE_TIME = 65  # (String) deviceOnlineTime
TP = 66  # (String) technical parameter
NVR_NEUTRAL_CHANNEL_CAPS = 67  # (JSON) nvrNeutralChannelCaps
NVR_NEUTRAL_QR_CODE_KEY = 68  # (String) nvrNeutralQrCodeKey
MEDIA_QUANTITY = 69  # (Int) mediaQuantity
AFTER_SALE = 70  # (Int) afterSale support status
DELETE_SD_FILES = 71  # (Action) delete files on SD
DEVICE_NAME = 72  # (String) Custom device name

WIFI_NAME = 100  # (String) Current WiFi SSID
ROTATE_ENABLE = 102  # (Int) 0: Normal, 1: Flipped 180°
LED_ENABLE = 103  # (Int) 0: Off, 1: On (Status LED)
NVR_CHANNEL_LED_ENABLE = 103  # (Int) duplicate ID for NVR LED
SD_RECORD_TYPE = 104  # (Int) 0: Continuous, 1: Event (Alarm)
PLAYBACK_RECORD_VIDEO_TYPE = 104  # (Int) duplicate ID for playback filtering
SD_RECORD_DURATION = 105  # (Int) duration in seconds
PLAYBACK_RECORD_VIDEO_DURATION = 105  # (Int) duplicate ID for record length
MOTION_DET_ENABLE = 106  # (Int) 0: Off, 1: On
# The app offers a 3-item Low/Medium/High picker whose values are per-model
# and can be inverted: R.array.motion_level_value = [6, 4, 2], while
# R.array.iot_sensitivity_value = [0, 1, 2]. Treated here as a plain numeric.
MOTION_DET_SENSITIVITY = 107  # (Int) model-dependent sensitivity
HUMAN_DET_ENABLE = 108  # (Int) 0: Off, 1: On (AI Human Detection)
SOUND_DET_ENABLE = 109  # (Int) 0: Off, 1: On
# App picker is Low/Medium/High over R.array.decibel_level_value = [2, 1, 0]
# (inverted: 0 is the most sensitive). Treated here as a plain numeric.
SOUND_DET_SENSITIVITY = 110  # (Int) model-dependent sensitivity
CRY_DET_ENABLE = 111  # (Int) 0: Off, 1: On (Baby Crying)
HUMAN_TRACK_ENABLE = 112  # (Int) 0: Off, 1: On (Auto Tracking)
DAY_NIGHT_MODE = 113  # (Int) 0: Automatic, 1: Day, 2: Night
SD_STATUS = 114  # (Int) 1: Normal, 2: Error, 3: Formatting, 4: No Card
SD_CAPACITY = 115  # (String) Total size (MB)
SD_REMAINING_CAPACITY = 116  # (String) Free space (MB)
HUMAN_FRAME_ENABLE = 117  # (Int) 0: Off, 1: On (Show AI box in stream)
SLEEP_MODE = 118  # (Int) 0: Lens Off/Sleep, 1: Lens On/Awake
SLEEP_TIME_LIST = 119  # (JSON) Schedule for sleep mode
SLEEP_WIFI = 120  # (String) sleep-mode wifi config (app reads it as a string)
ONVIF_ENABLE = 121  # (Int) 0: Off, 1: On
ONVIF_PWD = 122  # (String) ONVIF password (Base64)
ONVIF_URL = 123  # (String) ONVIF address
H265_ENABLE = 124  # (Int) 0: H.264, 1: H.265
ALARM_PLAN_LIST = 125  # (JSON) Alarm schedule list
IP = 126  # (String) Local IP address
NET_MODE = 127  # (Int) 0: WiFi, 1: Cable, 2: AP, 4: 4G
OTA_UPGRADE_STATUS = (
    128  # (Int) 0: Idle, 1: Downloading, 2: Upgrading, 3: Success, 4: Fail
)

CHIME_PRO_RING_URI = 131  # (String) Ringtone URI for Chime Pro
CHIME_PRO_RING_VOLUME = 132  # (Int) 0-100
CHIME_PRO_MOTION_URI = 133  # (String) Motion alert tone URI
CHIME_PRO_MOTION_VOLUME = 134  # (Int) 0-100
CHIME_PRO_RING_TYPE = 135  # (Int) Tone type index
CHIME_PRO_SNOOZE_INTERVAL = 136  # (Int) Minutes
CHIME_PLAN = 137  # (JSON) chimePlan list
RECORD_SWITCH = 140  # (Int) 0: Disable SD, 1: Enable SD recording
SMART_DET = 141  # (Int) 0: Off, 1: On (General Smart Detection)
SMART_DET_FRAME = 142  # (Int) 0: Off, 1: On (Show smart frames)
SMART_DET_SENSITIVITY = 143  # (Int) 1-5 Sensitivity
SMART_DET_DEPLOYMENT_TIME = 144  # (JSON) Detection schedule
TIMING_RECORD = 145  # (JSON) List of timed recording intervals

PIR_DET_ENABLE = 150  # (Int) 0: Off, 1: On (PIR Sensor)
# App picker uses R.array.pir_level_value = [1, 2, 3] (Low/Medium/High);
# some hardware exposes a wider range.
PIR_DET_SENSITIVITY = 151  # (Int) 1-3 in the app, wider on some hardware
SPEAK_VOLUME = 152  # (Int) 0-100 (Camera speaker volume)
POWER_TYPE = 153  # (Int) 0: Battery, 1: AC/Plugged
BATTERY_PERCENT = 154  # (Int) 0-100
BATTERY_REMAINING = 155  # (Int) Remaining minutes (estimated)
CHARGE_STATUS = 156  # (Int) 0: Not Charging, 1: Charging, 2: Full
WIRELESS_CHIME_ENABLE = 157  # (Int) 0: Off, 1: On (433MHz Chime)
WIRELESS_CHIME_VOLUME = 158  # (Int) 1-5 volume levels
WIRELESS_CHIME_SONGS = 159  # (String) available songs list
WIRELESS_CHIME_SELECT_SONG = 160  # (String) selected song
MECHANICAL_CHIME_ENABLE = 161  # (Int) 0: Off, 1: On (For doorbells)
TIME_FORMAT_SWITCH = 162  # (Int) 0: 12h, 1: 24h
MUSIC_PLAY_MODE = 162  # (Int) 0: Single, 1: Loop, 2: Random (duplicate ID)
OSD_STYLE = 162  # (Int) Style index (duplicate ID)
BELL_SLEEP_DELAY = 163  # (Int) Seconds before sleep
BELL_ENTER_MESSAGE_TIME = 164  # (Int) Seconds before voicemail starts
BELL_MAX_MESSAGE_TIME = 165  # (Int) Seconds max for voicemail
REMOVE_PROTECT_ALERT = 166  # (Int) 0: Off, 1: On (Anti-tamper alarm)
FLIGHT_LIGHT_SWITCH = 167  # (Int) 0: Off, 1: On (Floodlight manual)
FLIGHT_BRIGHTNESS = 168  # (Int) 1-100 (Floodlight brightness)
FLIGHT_SCHEDULE = 169  # (JSON) Floodlight timer
DOUBLE_PIR_STATUS = 170  # (Int) PIR configuration status
FLIGHT_PIR_DURATION = 171  # (Int) Seconds (light stays on after PIR)
HUMAN_DET_NIGHT_ENABLE = 173  # (Int) 0: Off, 1: On (Night AI)
HUMAN_DET_DAY_ENABLE = 174  # (Int) 0: Off, 1: On (Day AI)
ROI = 177  # (JSON) [{"x":0,"y":0,"w":100,"h":100}] Alarm area
# Alarm re-trigger interval, not a sensitivity. 0: Off, 1: 1min, 2: 2min,
# 3: 3min, 4: 5min, 5: 10min, 6: 30s. Offered subset comes from caps "afq" bits.
ALARM_FREQUENCY = 178  # (Int) interval enum; see select.py for the label map
MUSIC_VOLUME = 179  # (Int) 0-100
FLIGHT_LINK_LIGHTING_ENABLE = 180  # (Int) 0: Off, 1: Light up on motion
FACE_RECOGNITION_SWITCH = 181  # (Int) 0: Off, 1: On
SOUND_LIGHT_ENABLE = 182  # (Int) 0: Off, 1: On (Siren + Flash)
SOUND_LIGHT_TYPE = 183  # (Int) 0: Audio, 1: White light, 2: Audio + strobe
COME_DEVICE_VOLUME = 184  # (Int) Volume for response messages
FLIGHT_MANUAL_LIGHTING_DURATION = 185  # (Int) Minutes
FLIGHT_MULTI_SCHEDULE = 186  # (JSON) lightingPlanList
FLIGHT_LINK_SIREN_ENABLE = 187  # (Int) 0: Off, 1: Siren on motion
OSD_ENABLE = 190  # (Int) 0: Off, 1: On (Timestamp on video)
LOGO_SWITCH = 191  # (Int) 0: Off, 1: On (Watermark)
USER_ACCOUNT = 193  # (String) Associated account
RELAY_ENABLE = 194  # (Int) 0: Off, 1: On (Relay Control)
ABNORMAL_NOISE_ENABLE = 195  # (Int) 0: Off, 1: On (Noise detection)
TIMED_PTZ_PATROL = 196  # (JSON) patrol time list (app: setPatrolTimeList)
RGB_LIGHT_SWITCH = 197  # (Int) 0: Off, 1: On
RGB_LIGHT_COLOR = 198  # (JSON) "[r,g,b]" array, e.g. "[255,255,0]"
RGB_LIGHT_TIMING = 199  # (JSON) RGB timer schedule
RGB_LIGHT_MODE = 200  # (Int) Mode index
PIR_JIM = 201  # (Int) Work mode for battery devices (Power saving)
NO_FLK = 202  # (Int) 0: 50Hz, 1: 60Hz (Anti-flicker)
AUTO_UPDATE = 203  # (Int) 0: Off, 1: On (Auto OTA)
DEVICE_WAKE = 205  # (String) wake alert time (app: setWakeAlertTime)
HOMEKIT_ENABLE = 206  # (Int) 0: Off, 1: On
MEN_PHONE = 207  # (Int) 0: Off, 1: On (Microphone switch)
SEN_SOUND = 208  # (Int) 0: Off, 1: On (Speaker switch)
# 0: Intelligent vision, 1: Full colour night vision, 2: B/W night vision.
# Variant hardware offers other value sets (e.g. [1, 5] or [0, 1, 2, 3]).
FULL_COLOR_MODE = 209  # (Int) night-vision mode enum
RAE_SOUND = 211  # (Int) 0: Off, 1: On (Rae/Alarm Audio)
BELL_PHONE = 212  # (String) doorbell call target (app: setBellPhone)
NVR_NEUTRAL_CHANNEL_MAX = 213  # (Int) Max channels supported
NVR_NEUTRAL_QR_CODE_STRING = 214  # (String) QR Code for pairing
NVR_NEUTRAL_DISK_STATUS = 215  # (JSON) Disk info for NVR
VIDEO_PWD_IS_SET = 216  # (Int) 0: No, 1: Yes (Video encryption)
VIDEO_PWD = 217  # (String) Video encryption password
SOT_TIME = 218  # (Int) Screen-on time / Sleep timeout
TIME_ZONE_AUTO = 219  # (Int) 0: Manual, 1: Auto sync from phone
TIME_ZONE_TIME = 220  # (String) Current device time
DEVICE_ICCID = 221  # (String) SIM Card ICCID
DEVICE_IMEI = 222  # (String) IMEI for 4G devices
ANTI_JAMMING = 223  # (Int) 0: Off, 1: On
HUMAN_SENSITIVITY_LEVEL = 224  # (Int) 1: Low, 2: Med, 3: High
FRAME_RATE = 228  # (Int) Video frames per second
PLUG_LOW_POWER_MODE = 229  # (Int) 0: Off, 1: On
SOUND_LIGHT_ALARM_PLAN_LIST = 230  # (JSON) Siren/Light schedule
LIGHT_SOUND_SELECT_SONG = 231  # (Int) Song index for alarm
POLYGON_ROI = 232  # (JSON) Custom polygon coordinates
MULTIPLE_VIDEO = 232  # (JSON) Multiple view configuration (duplicate ID)
POLYGON_PRIVACY = 233  # (JSON) Privacy masking areas
UPLOAD_VIDEO = 235  # (Int) 0: Off, 1: On (Upload to cloud)
PET_THROW_WARNING = 236  # (Int) 0: Off, 1: On (Pet feeder alert)
PET_FEED_PLAN_LIST = 237  # (JSON) Feeding schedule
REMOTE_AWAKE = 238  # (Int) 0: Off, 1: On (Remote wake support)
INFRARED_LIGHT = 238  # (Int) 0: Off, 1: On, 2: Auto (duplicate ID)
TIMING_SHOT = 239  # (Int) Seconds between snapshots
MONITOR_TIME_SWITCH = 240  # (Int) 0: Off, 1: On
MONITOR_TIME = 241  # (JSON) Monitoring intervals
TEMP_HUMIDITY_ENABLE = 241  # (Int) 0: Off, 1: On (duplicate ID)
PIR_TRIGGER_INTERVAL = 242  # (Int) Seconds (Cooldown between PIR)
TEMPERATURE_MAX = 242  # (Int) Milli-degrees C alarm limit (duplicate ID)
WIFI_ACCOUNT_AND_PASSWORD = 243  # (JSON) {"s":"SSID","p":"PWD"}
TEMPERATURE_MIN = 243  # (Int) Milli-degrees C alarm limit (duplicate ID)
KEY_VOICE_SWITCH = 244  # (Int) 0: Mute, 1: Beep (Button sounds)
HUMIDITY_MAX = 244  # (Int) Milli-percent RH alarm limit (duplicate ID)
BLE_SWITCH = 245  # (Int) 0: Off, 1: On (Bluetooth)
HUMIDITY_MIN = 245  # (Int) Milli-percent RH alarm limit (duplicate ID)
SHOT_TYPE = 246  # (Int) 0: Photo, 1: Video
SWITCH_DEVICE_WIFI = 246  # (Action) Switch to another SSID (duplicate ID)
SHOT_RESOLUTION = 247  # (Int) 0: HD, 1: SD
SMART_POLYGON_ROI = 247  # (JSON) Polygon for AI (duplicate ID)
SHOT_NUM = 248  # (Int) Number of shots per trigger
RECORD_RESOLUTION = 249  # (Int) 0: HD, 1: SD
HUNTING_RECORD_DURATION = 250  # (Int) Seconds
RESTORE_FACTORY = 251  # (Action) Factory reset
TIMING_SHOT_SWITCH = 252  # (Int) 0: Off, 1: On
HUNTING_DOUBLE_PIR = 253  # (Int) PIR mode for hunting
POWER_UP_PASSWORD_ENABLE = 254  # (Int) 0: Off, 1: On
POWER_UP_PASSWORD = 255  # (String) Password
LANGUAGE = 256  # (Int) 0: CN, 1: EN, 2: IT, etc.
TURN_OFF_WIFI_DURATION = 257  # (Int) Minutes
SOUND_SWITCH = 258  # (Int) 0: Mute, 1: Sound On
SOUND_DATE = 259  # (JSON) Sound files list
SWITCH_WIFI = 260  # (Action) Trigger WiFi change
SOUND_SET = 262  # (Int) 0-100 (Master volume)
PET_ALARM = 263  # (Int) 0: Off, 1: On (Barking detection)
PET_ALARM_ENABLE = 264  # (Int) 0: Off, 1: On
LOW_THRESHOLD = 266  # (Int) Battery low warning %
FULL_TIME_FRAME_RATE = 267  # (Int) FPS for continuous recording
SIM_INDEX = 269  # (Int) 0 or 1 (Active SIM)
SIM_MSG = 270  # (String) SIM Status / Info
AOV_RECORD_DELAY = 272  # (Int) Seconds (Always-On-Video delay)
AOV_COMPLEMENTARY_DISTANCE = 273  # (Int) Fill-light distance
AOV_NIGHT_MODE = 274  # (Int) 0: B/W, 1: Color
AOV_WORK_MODE = 275  # (Int) 0: Power save, 1: Balance, 2: Performance
MUSIC_TIME = 276  # (Int) Playback duration
MUSIC_CYCLICAL = 277  # (Int) 0: No loop, 1: Loop
WATCH_SLOT = 278  # (Int) Preset position index (1-6)
ALARM_SOUND_LIGHT_SET = 280  # (JSON) Siren + Light configuration
LOCATOR_WORK_MODE = 282  # (Int) GPS/Locator mode
TIMING_MODE = 283  # (JSON) {"from":"18:00","to":"8:00"} timed work mode
POWER_ON_VOICE_ENABLE = 284  # (Int) 0: Off, 1: On (Startup sound)
POWER_ON_VOLUME = 285  # (Int) 0-100
COVER_DET_ENABLE = 286  # (Int) 0: Off, 1: On (Lens cover detection)
DOWN_DET_ENABLE = 287  # (Int) 0: Off, 1: On (Fall detection)
SIM_OPERATORS = 288  # (String) Carrier name
WARM_LIGHT_BRI = 289  # (Int) 1-100 (Warm light brightness)
SD_STATUS_2 = 290  # (Int) Status for secondary SD
LASER_SWITCH = 291  # (Int) 0: Off, 1: On (Laser pet toy)
TEASE_MODE = 292  # (Int) 0: Manual, 1: Auto (Pet teasing)
TEASE_DURATION = 293  # (Int) Minutes
TEASE_PLAN = 294  # (JSON) Schedule for pet teasing
LOCATOR_LIGHT = 295  # (Int) 0: Off, 1: On
LOCATOR_SOUND = 296  # (Int) 0: Off, 1: On
SIM_IS_ESIM = 297  # (String) physical SIM vs eSIM (app reads it as a string)
SMART_DET_FRONT = 299  # (Int) Front camera detection
SMART_DET_FRONT_FRAME = 300  # (Int) Front camera frames
SMART_DET_FRONT_SENSITIVITY = 301  # (Int) 1-5
SMART_DET_FRONT_DEPLOYMENT_TIME = 302  # (JSON) Front schedule
SMART_FRONT_POLYGON_ROI = 303  # (JSON) Front polygon area

RESET_DEVICE = 800  # (Action) Soft reset
RESET_DEVICE_1 = 801  # (Action) Hard reset
SYNC_TIME = 802  # (Action) Sync time with phone
OTA_UPGRADE = 803  # (Action) Start firmware upgrade
DEVICE_WIFI_LIST = 804  # (Action) Get nearby WiFi list
FORMAT_SDCARD = 806  # (Action) Format SD card
START_PTZ = 807  # (Action) Start PTZ movement (JSON: direction, speed)
STOP_PTZ = 808  # (Action) Stop PTZ movement
REFRESH_PROPERTY = 809  # (Action) Refresh all properties/SD info
BIND_WIRELESS_CHIME = 811  # (Action) Enter pairing mode for Chime
UNBIND_WIRELESS_CHIME = 812  # (Action) Unpair Wireless Chime
UNLOCK_BATTERY = 813  # (Action) Eject battery (for specific models)
RELAY = 816  # (Action) Trigger relay pulse
MUSIC_PLAY_CONTROL = 821  # (Int) 0: Stop, 1: Play, 2: Pause, 3: Next, 4: Prev
PTZ_PATROL = 822  # (Int) 0: Stop, 1: Start Patrol
FLIGHT_SIREN_SWITCH = 823  # (Int) 0: Off, 1: Siren On (Manual)
RELAY_STATUS = 824  # (Int) 0: Open, 1: Closed
ALL_ALARMS = 825  # (Int) 0: Master Off, 1: Master On
JINGLE_PLAN = 827  # (JSON) Schedule for Jingle/Chime
JINGLE_PLAN_ENABLE = 828  # (Int) 0: Off, 1: On
JINGLE_VOLUME = 829  # (Int) 0-100
REMOVE_NVR_IPC = 830  # (Int) IPC Index to remove
ALLOW_DISCOVERED = 831  # (Int) 0: Hidden, 1: Discoverable
NVR_START_SEARCH_DEVICE = 832  # (Action) Search for IPCs
NVR_ADD_DEVICE = 833  # (JSON) IPC info to add
NVR_REQUEST_ADD_DEVICE = 836  # (JSON) Add request
RECEPTACLE_SWITCH = 837  # (Int) 0: Off, 1: On (Smart Plug)
START_PTZ_2 = 841  # (Action) Movement for secondary PTZ
STOP_PTZ_2 = 842  # (Action) Stop secondary PTZ
PET_SOUND_SET = 843  # (Int) Sound ID for feeding
PET_FEED_CALL = 844  # (Action) Play feeding voice
PET_FEED = 845  # (Action) Trigger manual feeding
JINGLE_AUTO_ADD_DEVICE = 846  # (Int) 0: Off, 1: On (Auto-pair Chime)
PTZ_CALIBRATION = 847  # (Action) Start self-calibration
PTZ_PRESET = 848  # (JSON) {"id":1, "name":"door", "act":"set/goto/del"}
CAMERA_LINKAGE = 849  # (JSON) Linkage rules between devices
PET_FEED_2 = 850  # (Int) Portions to dispense
CAMERA_CONTROL = 851  # (Int) 0: Off, 1: On (Privacy lens)
LOCATOR_SEND_MODE = 852  # (Int) Mode index
LOCATOR_BLE = 854  # (Int) 0: Off, 1: On
PET_SOUND_CALL = 860  # (Action) Play voice call
SELECT_SIM = 861  # (Int) SIM 1 or 2
SCREEN_CONNECT_STATUS = 862  # (Int) 0: Disc, 1: Conn
BABY_STATUS = 863  # (Int) 0: Awake, 1: Crying, 2: Sleeping

OTA_UPGRADE_DOWNLOAD = 1001  # (Int) Download progress 0-100
OTA_UPGRADE_UPDATE = 1002  # (Int) Update progress 0-100
OTA_UPGRADE_TOTAL = 1003  # (Int) Total progress 0-100
SD_FORMAT_PROGRESS = 1004  # (Int) Formatting progress 0-100
WIFI_STRENGTH = 1007  # (Int) 0-100 (Signal intensity)
TEMPERATURE = 1008  # (Int) Milli-degrees C; 21560 -> 21.56 degC, 255000 = none
HUMIDITY = 1009  # (Int) Whole percent RH (not milli-scaled); 255 = none
FLIGHT_LIGHT_STATUS = 1010  # (Int) 0: Off, 1: On
MUSIC_STATUS = 1012  # (Int) 0: Stopped, 1: Playing
FLIGHT_SIREN_DURATION = 1013  # (Int) Remaining siren seconds
RGB_LIGHT_STATUS = 1014  # (Int) 0: Off, 1: On
NVR_NEUTRAL_CHANNEL_STATUS = 1015  # (JSON) Status of all channels
ALLOW_DISCOVERED_TIME_LEFT = 1018  # (Int) Seconds remaining for discovery
NVR_GET_SEARCH_RESULT = 1019  # (JSON) List of found devices
SLEEP_STATUS = 1020  # (Int) 0: Awake, 1: Sleeping
DEVICE_CONFIG_ERROR_CODE = 1028  # (Int) Last error code
DEVICE_APN_INFO = 1029  # (String) APN string for 4G
WIFI_CONNECT_STATE = 1030  # (Int) 0: Disconnected, 1: Connected, 2: Connecting
DEVICE_RESET_STATUS = 1031  # (Int) 0: Normal, 1: Resetting
DEVICE_WIFI_INFO = 1032  # (JSON) SSID, IP, RSSI
PTZ_INFO = 1034  # (JSON) Current X, Y coordinates
GET_MRDA_VITAL_SIGN_DATA = 1040  # (JSON) Health monitoring data
DEVICE_SIM_INFO = 1042  # (JSON) Operator, Signal, Data used
DEVICE_CONFIG_ERROR_CODE_2 = 1044  # (Int) Extended error code

MQTT_IOT_FIRST_KEY = "items"  # Root key for MQTT JSON
MQTT_IOT_THIRD_KEY = "value"  # Value key for MQTT JSON
COMM_PASSWORD = ""  # Default empty communication pwd
